apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    imagePullSecrets:
    - name: String
    volumeMounts:
    - mountPath: /mydata
      name: nginx-data
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: tttttttttttttttttest
