apiVersion: v1
kind: Pod
metadata:
 name: nginx-pod
spec:
  containers:
  - name: nginx
    image: 192.168.154.132/library/nginx:alpine
    ports:
    - containerPort: 80
    imagePullSecrets:
    - name: String

